---
type: Handler
api_version: core/v2
metadata:
  name: telegram
  labels:
    sensu.io/workflow: sensu-flow
spec:
  command: sensu-telegram-handler --api-token "${TELEGRAM_API_TOKEN}" --chatid "${TELEGRAM_CHAT_ID}"
  type: pipe
  filters:
    - is_incident
    - not_silenced
  runtime_assets:
    - telegram-handler
  secrets:
    - name: TELEGRAM_API_TOKEN
      secret: telegram-api-token
    - name: TELEGRAM_CHAT_ID
      secret: telegram-chat-id
